//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.ClientInfoes = new HashSet<ClientInfo>();
            this.Credits = new HashSet<Credit>();
            this.Deposits = new HashSet<Deposit>();
        }
    
        public int Id { get; set; }
        public int UserProfileId { get; set; }
        public string IdentityNumber { get; set; }
        public string PassportSerialNumber { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<ClientInfo> ClientInfoes { get; set; }
        public virtual ICollection<Credit> Credits { get; set; }
        public virtual ICollection<Deposit> Deposits { get; set; }
    }
}
