//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.ClientInfo = new HashSet<ClientInfo>();
            this.Credit = new HashSet<Credit>();
            this.Deposit = new HashSet<Deposit>();
        }
    
        public int Id { get; set; }
        public int AccountId { get; set; }
        public string IdentityNumber { get; set; }
        public string PassportSerialNumber { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<ClientInfo> ClientInfo { get; set; }
        public virtual ICollection<Credit> Credit { get; set; }
        public virtual ICollection<Deposit> Deposit { get; set; }
    }
}
