//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credit
    {
        public Credit()
        {
            this.CreditPayment = new HashSet<CreditPayment>();
        }
    
        public int Id { get; set; }
        public System.DateTime StartDate { get; set; }
        public decimal StartAmount { get; set; }
        public decimal MainDebt { get; set; }
        public int CreditTypeId { get; set; }
        public Nullable<int> RequestId { get; set; }
        public int ClientId { get; set; }
        public decimal PercentageDebt { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool IsClosed { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual CreditType CreditType { get; set; }
        public virtual Request Request { get; set; }
        public virtual ICollection<CreditPayment> CreditPayment { get; set; }
    }
}
