//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credit
    {
        public Credit()
        {
            this.Transaction = new HashSet<Transaction>();
            this.Client = new HashSet<Client>();
        }
    
        public int Id { get; set; }
        public System.DateTime StartDate { get; set; }
        public decimal StartAmount { get; set; }
        public decimal Debt { get; set; }
        public int CreditTypeId { get; set; }
    
        public virtual ICollection<Transaction> Transaction { get; set; }
        public virtual ICollection<Client> Client { get; set; }
    }
}
